config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    path: '',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  },
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  resources :courses
  resources :comments
  resources :request_courses
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :new, :destroy]
  before_action :authenticate_user!
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    respond_to do |format|
      format.html
      format.json { render json: @courses}
    end
  end

  # GET /courses/1
  # GET /courses/1.jsn
  def show
    respond_to do |format|
      format.html
      format.json { render json: @course}
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  def check_user
    unless current_user.teacher?
      redirect_to courses_path, alert: 'Unauthorized access!'
    end
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:title, :content, :start_datetime, :end_datetime, :length_of_students)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :start_datetime %>
    <%= form.datetime_select :start_datetime, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :end_datetime %>
    <%= form.datetime_select :end_datetime, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :length_of_students %>
    <%= form.number_field :length_of_students, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit%>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="container">
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
<h1>Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Start datetime</th>
      <th>End datetime</th>
      <th>Length of students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.content %></td>
        <td><%= course.start_datetime %></td>
        <td><%= course.end_datetime %></td>
        <td><%= course.length_of_students %></td>
        <td><%= link_to 'Show', course %></td>
        <% if current_user.teacher? %>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to 'Join', "/request_courses?course_id=#{course.id}", method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', root_path %> |
<%= link_to 'New Course', new_course_path if current_user.teacher? %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<div class = "container">
  <p>
    <strong>Title:</strong>
    <%= @course.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @course.content %>
  </p>

  <p>
    <strong>Start datetime:</strong>
    <%= @course.start_datetime %>
  </p>

  <p>
    <strong>End datetime:</strong>
    <%= @course.end_datetime %>
  </p>

  <p>
    <strong>Length of students:</strong>
    <%= @course.length_of_students %>
  </p>

  <h3>Comments</h3>
  <% @course.comments.each do |comment| %>
    <div>
      <strong><%= comment.user.email %></strong>
      <br>
      <p><%= comment.comment %></p>
      <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } if current_user == comment.user %></p>
    </div>
  <% end %>


  <%= render 'comments/form', comment: Comment.new, course_id: @course.id %>
  <%= link_to 'Edit', edit_course_path(@course) %> |
  <%= link_to 'Back', courses_path %>
</div>