config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    path: '',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  },
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  resources :courses
  resources :comments
  resources :request_courses
end

app/controllers/request_courses_controller.rb
class RequestCoursesController < ApplicationController
  before_action :set_req_course, only: [:show, :update, :edit]
  before_action :authenticate_user!

  def index
    @q = current_user.request_courses.ransack(params[:q])
    @request_courses = @q.result
    @request_courses = RequestCourse.all if current_user.teacher?
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @courses}
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @course}
    end
  end

  def edit
  end

  def create
    if current_user.request_courses.this_month.count <= 2
      @request_courses = current_user.request_courses.build(course_id: params[:course_id])
      respond_to do |format|
        if @request_courses.save
          format.html { redirect_to courses_path, notice: 'Course join request was successfully created.' }
          format.json { render json: @request_courses }
        else
          format.html { redirect_to courses_path, alert: 'You have already joined this course' }
          format.json { render json: @request_courses.errors }
        end
      end
    else
      redirect_to courses_path, notice: "You can't join more than 3 in a month"
    end
  end

  def update
    respond_to do |format|
      if @request_course.update(status: params[:request_course][:status])
        format.html { redirect_to @request_course, notice: "Updated successfully!" }
      else
        format.html { render :edit }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_req_course
    @request_course = RequestCourse.find(params[:id])
  end

end

app/views/request_courses/_form.html.erb
<%= form_with(model: request_course, local: true) do |form| %>
  <% if request_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_course.errors.count, "error") %> prohibited this request_course from being saved:</h2>

      <ul>
        <% request_course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, [:accept, :rejected] , class: "form-control" if current_user.teacher? %>
    <%= form.select :status, [:done] , class: "form-control" if current_user.student? %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/request_courses/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @request_courses.each do |request_course| %>
      <tr>
        <td><%= request_course.user.name if current_user.teacher? %></td>
        <td><%= link_to "#{request_course.course.title}", request_course.course %></td>
        <td><%= request_course.status %></td>
        <td><%= link_to 'Show', request_course %></td>
        <td><%= link_to 'Edit', edit_request_course_path(request_course) if current_user.teacher? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/request_courses/edit.html.erb
<div class="container">
  <h1>Editing Request Course</h1>

  <%= render 'form', request_course: @request_course %>

  <%= link_to 'Show', @request_course %> |
  <%= link_to 'Back', request_courses_path %>
</div>

app/views/request_courses/index.html.erb
<% if current_user.student? %>
  <%= search_form_for @q, remote: true do |f| %>
    <%= f.select(:status_eq, RequestCourse.statuses.to_a.map { |w| [w[0].humanize, w[1]] } ,{:include_blank => true}, {class: "form-control select2"}) %><br>
    <%= f.submit "Search", class: "btn btn-success float-right ml-2"%>
  <% end %>
<% end %>

<h1>Request Courses</h1>
<div id="course_list">
  <%= render 'list' %>
</div>
<%= link_to 'Back', root_path %>

app/views/request_courses/index.js.erb
$('#course_list').html("<%= j render(partial: 'list') %>");

app/views/request_courses/show.html.erb
<div class = "container">
  <p>
    <strong>Course:</strong>
    <%= @request_course.course.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @request_course.status %>
  </p>

  <%= link_to 'Edit', edit_request_course_path(@request_course) %> |
  <%= link_to 'Back', request_courses_path %>
</div>